version: '3.8'

services:
  web:
    build: .
    command: /bin/sh -c "sleep 3 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fast_food_db
      - POSTGRES_USER=fast_food_user
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
      

volumes:
  postgres_data: