# Generated by Django 4.2.3 on 2023-10-27 17:26

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(10.0, 40.0), srid=4326),
            preserve_default=False
        ),
    ]
