# Generated by Django 4.2.3 on 2023-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_dish_created_at_dish_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.dish'),
        ),
        migrations.DeleteModel(
            name='OrderedDishes',
        ),
    ]
