# Generated by Django 4.2.3 on 2023-10-28 08:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_dishes_delete_ordereddishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(10.0, 40.0), srid=4326),
            preserve_default=False
        ),
    ]
