# Generated by Django 4.2.3 on 2023-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('base_user', 'Base User')], default='base_user', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(help_text='User Images', null=True, upload_to='user'),
        ),
    ]
