# Generated by Django 4.2.3 on 2023-10-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_type_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='role',
        ),
    ]
